# The Journey

This section describes the decisions taken to get to our final solution
 

## The Baseline

This section is the code we were given

In [10]:
# requires sciket-learn 0.18
# if required, conda update scikit-learn

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import roc_curve, auc
from sklearn.grid_search import GridSearchCV   #Performing grid search


def readFiles():
    #Reading files
    X = pd.read_csv("trainingData.txt",sep='\t',header=None)
    Y = pd.read_csv("trainingTruth.txt",sep='\t',header=None)
    Y = np.array(Y).ravel()
    
    return (X,Y)


def preprocessFeatures1( X ):
    print('Preprocessing data (1).')
    
    # Replace NAs with 0
    X = X.fillna(0) 
    
    return X


def runModel1(X,Y):
    print('Run model')
    
    clf = OneVsRestClassifier(RandomForestClassifier(n_estimators = 10,random_state=25))
    clf.fit(X,Y)
    Y_predict = clf.predict_proba(X)
    
    return Y_predict, clf


def calculateROC(Y, Y_predict):
    print('Calc ROC')
    # Binarize the output
    y_bin = label_binarize(Y, classes=[1, 2, 3,4])

    #Calculate AUC
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(4):
        fpr[i], tpr[i], _ = roc_curve(y_bin[:, i], Y_predict[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    return roc_auc

def createSubmission(clf, preprocessData=preprocessFeatures1):
    #Create submission
    Xtest = pd.read_csv("testData.txt",sep="\t",header=None)
    
    (Xtest) = preprocessData(Xtest)
    y_final_prob = clf.predict_proba(Xtest)
    y_final_label = clf.predict(Xtest)

    print(y_final_prob)
    print(y_final_label)
    
    sample = pd.DataFrame(np.hstack([y_final_prob.round(5),y_final_label.reshape(y_final_prob.shape[0],1)]))
    sample.columns = ["prob1","prob2","prob3","prob4","label"]
    sample.label = sample.label.astype(int)
    
    #Submit this file to dropbox
    sample.to_csv("Johnston_Memic_1.csv",sep="\t" ,index=False,header=None)
    

# Read the files in.   
(XOrig,YOrig) = readFiles()


# Clean up the data
X = preprocessFeatures1(XOrig)
Y = YOrig

# Run the model
Y_predict, clf = runModel1(X,Y)

baselineAUC = calculateROC(Y, Y_predict)

print('Baseline AUC is: ', baselineAUC)

createSubmission(clf)




Preprocessing data (1).
Run model
Calc ROC
Baseline AUC is:  {0: 0.99996212682662722, 1: 0.99993172956870668, 2: 0.99996736488783788, 3: 0.99986086891635195}
Preprocessing data (1).
[[ 0.          0.14285714  0.42857143  0.42857143]
 [ 0.2         0.2         0.4         0.2       ]
 [ 0.8         0.          0.2         0.        ]
 ..., 
 [ 0.7         0.          0.1         0.2       ]
 [ 0.375       0.25        0.375       0.        ]
 [ 0.46153846  0.23076923  0.07692308  0.23076923]]
[4 3 1 ..., 1 3 1]


## Pre-processing the data



### Analysing NAs

First we analyse the prevalance on NAs in our features. For each feature, we calculate the frequency of NAs. This will help determine whether we think the feature is worth keeping as too many NAs indicates that the feature is not giving us enough information.


In [2]:
from scipy.stats import itemfreq

X = XOrig
Y = YOrig

sums = {}

total = X.shape[0]

for col in X.columns:
    # Count the NAs
    sums[col] = total - X[col].count()
    
# Do something more clever here? Plot a distribution?
#print(sums)
print('Maximum number of NAs in one column: ', max(sums.values()))
print('Minimum number of NAs in one column: ', min(sums.values()))

# Check the rows to see if there are any rows with excessive NAs
rowSums = X.isnull().sum(axis=1).tolist()
print('Maximum number of NAs in one row: ', max(rowSums))
print('Minimum number of NAs in one row: ', min(rowSums))

X.describe()

# Histogram of each variable?

Maximum number of NAs in one column:  81
Minimum number of NAs in one column:  40
Maximum number of NAs in one row:  7
Minimum number of NAs in one row:  0


/Users/rob/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


0             1             2             3             4    \
count  17321.000000  17325.000000  17312.000000  17322.000000  17324.000000   
mean       0.264572      0.456596      0.435167      0.263299      0.496509   
std        0.455943      0.513085      0.509448      0.452074      0.513279   
min       -1.560800     -1.506400     -1.399000     -1.488200     -1.442100   
25%             NaN           NaN           NaN           NaN           NaN   
50%             NaN           NaN           NaN           NaN           NaN   
75%             NaN           NaN           NaN           NaN           NaN   
max        2.054600      2.519100      2.413700      2.129900      2.335800   

                5             6             7             8             9    \
count  17324.000000  17317.000000  17333.000000  17326.000000  17297.000000   
mean       0.356921      0.362990      0.275144      0.423023      0.454524   
std        0.495707      0.498107      0.463826      0.503520      0.513399   
min       -1.306400     -1.884400     -1.721200     -1.444100     -1.578400   
25%             NaN           NaN           NaN           NaN           NaN   
50%             NaN           NaN           NaN           NaN           NaN   
75%             NaN           NaN           NaN           NaN           NaN   
max        2.251800      2.335600      2.086000      2.452100      2.486900   

           ...                324           325           326           327  \
count      ...       17321.000000  17311.000000  17331.000000  17316.000000   
mean       ...           0.448383      0.481281      0.277807      0.333366   
std        ...           0.512189      0.520883      0.460411      0.485206   
min        ...          -1.448600     -1.398600     -1.570100     -1.847300   
25%        ...                NaN           NaN           NaN           NaN   
50%        ...                NaN           NaN           NaN           NaN   
75%        ...                NaN           NaN           NaN           NaN   
max        ...           2.433600      2.372700      2.028400      2.522400   

                328           329           330           331           332  \
count  17314.000000  17312.000000  17310.000000  17314.000000  17319.000000   
mean       0.474403      0.273570      0.447165      0.487169      0.267626   
std        0.518349      0.460108      0.513640      0.512102      0.456374   
min       -1.626700     -1.865800     -1.403600     -1.628900     -1.696800   
25%             NaN           NaN           NaN           NaN           NaN   
50%             NaN           NaN           NaN           NaN           NaN   
75%             NaN           NaN           NaN           NaN           NaN   
max        2.303300      2.020800      2.578200      2.407200      2.070000   

                333  
count  17334.000000  
mean       0.389999  
std        0.503755  
min       -1.466600  
25%             NaN  
50%             NaN  
75%             NaN  
max        2.387100  

[8 rows x 334 columns]

In [3]:
# What's the distribution of outcomes?
print('\nDistribution of truth values.')
itemFrequencies = itemfreq(Y)
for freq, count in itemFrequencies:
    print('Frequencies:  ', freq, ': ', count/total, '%')


Distribution of truth values.
Frequencies:   1 :  0.326101968006 %
Frequencies:   2 :  0.224018874439 %
Frequencies:   3 :  0.300207158476 %
Frequencies:   4 :  0.149671999079 %


### NAs Replaced with Mean
We first looked at the treatment of nulls. The first step is, instead of replacing NAs with 0, replace them with the mean of the feature.

In [4]:


def preprocessFeatures3( X ):
    print('Preprocessing data (3).')

    # Q: Normalise data for SVMs - what about decision trees?
    

    #Rewrite this from the HW ipython book
    # Replace any NaN in X with the mean of the column
    # Replacing with the mean gives a better score
    xMean = []
    for col in X.columns:
        xMean = X[col].mean()
        #print(col, ' ', xMean)
        X.loc[X[col].isnull(), col] = xMean
    
    return (X)


# Clean up the data
X = preprocessFeatures3(XOrig)
Y = YOrig

# Run the model
Y_predict, clf = runModel1(X,Y)

meanNAAUC = calculateROC(Y, Y_predict)

print('Baseline AUC is: ', baselineAUC)
print('Mean NA AUC is: ', meanNAAUC)




Preprocessing data (3).
Run model
Calc ROC
Baseline AUC is:  {0: 0.99996212682662722, 1: 0.99993172956870668, 2: 0.99996736488783788, 3: 0.99986086891635195}
Mean NA AUC is:  {0: 0.99998479648620131, 1: 0.99993036758884135, 2: 0.99994417906316257, 3: 0.99988691290227649}


## Feature Selection

Run a RFC to see feature importance?
Plot histograms of all features?

See other notebook.

## First Submission

Our first submission on Wednesday was a basic RFC. The intention was to understand the process of sumbitting a file for the homework and to see just how bad a classifier this was!

In [13]:
# This takes 86 min to run. Set to True if you want to run it, otherwise
# the results will be taken from a previous run. The purpose of this was to run
# a Grid Search to find best parameters for a random forest classifier.
runLongRunningTest = True

def runModelWedSubmission(X,Y):
    print('Run model')
    
    #model_to_set = OneVsRestClassifier(RandomForestClassifier())

    #param_test1 = {'estimator__n_estimators':[10,20,30,40,50], 'estimator__max_depth':[3,6,8,12,24,32], 
    #           'estimator__min_samples_split':[2,4,6],'estimator__min_samples_leaf':[1,2,4]}
    
        
    #gsearch1 = GridSearchCV(estimator = model_to_set, 
    #                    param_grid = param_test1,n_jobs=8,iid=False, cv=5,verbose=2)
    #gsearch1.fit(X,Y)

    #Y_predict = gsearch1.predict_proba(X)
    
    #print('Best Params: ', gsearch1.best_params_)
    #print( 'Best Score: ', gsearch1.best_score_)

    clf = OneVsRestClassifier(RandomForestClassifier(n_estimators = 50,
                                                     max_depth = 32,
                                                     min_samples_split = 4,
                                                     min_samples_leaf = 4,
                                                     random_state=25))
    clf.fit(X,Y)
    Y_predict = clf.predict_proba(X)
    
    print(Y_predict)
    
    return Y_predict, clf


# Clean up the data
X = preprocessFeatures3(XOrig)



if runLongRunningTest:
    # Run the model
    Y_predict, clf = runModelWedSubmission(X,Y)

    wedSubmissionAAUC = calculateROC(Y, Y_predict)
    createSubmission(clf)
else:
    # Results from previous run:
    #  [Parallel(n_jobs=8)]: Done 1350 out of 1350 | elapsed: 89.6min finished
    # Best Params:  {'estimator__max_depth': 32, 'estimator__min_samples_split': 4, 'estimator__n_estimators': 50, 'estimator__min_samples_leaf': 4}
    # Best Score:  0.6728624493424956
    wedSubmissionAAUC =  {0: 0.99999891511100747, 1: 1.0, 2: 0.99999372674492126, 3: 1.0}


print('Baseline AUC is: ', baselineAUC)
print('Wednesday AUC is: ', wedSubmissionAAUC)



Preprocessing data (3).
Run model
[[ 0.15314808  0.13201841  0.59374422  0.12108929]
 [ 0.12497344  0.13698089  0.62803318  0.11001249]
 [ 0.06096861  0.10417378  0.77237967  0.06247794]
 ..., 
 [ 0.72407886  0.0950201   0.11974048  0.06116057]
 [ 0.75884939  0.08661501  0.05836962  0.09616598]
 [ 0.62097359  0.13794733  0.15715852  0.08392056]]
Calc ROC
Preprocessing data (1).
[[ 0.26261421  0.20209048  0.4370672   0.09822811]
 [ 0.15628277  0.1781048   0.54822087  0.11739156]
 [ 0.24468096  0.20983516  0.3242608   0.22122307]
 ..., 
 [ 0.57372334  0.23115142  0.13498655  0.06013869]
 [ 0.38670459  0.24346528  0.24110533  0.12872479]
 [ 0.46871942  0.3022865   0.14296728  0.08602681]]
[3 3 3 ..., 1 1 1]
Baseline AUC is:  {0: 0.99996212682662722, 1: 0.99993172956870668, 2: 0.99996736488783788, 3: 0.99986086891635195}
Wednesday AUC is:  {0: 0.99999984932097319, 1: 1.0, 2: 0.9999925761227586, 3: 1.0}


## Thursday Submission

In [ ]:
Preprocessing data (3).
Run model
[[ 0.15314808  0.13201841  0.59374422  0.12108929]
 [ 0.12497344  0.13698089  0.62803318  0.11001249]
 [ 0.06096861  0.10417378  0.77237967  0.06247794]
 ..., 
 [ 0.72407886  0.0950201   0.11974048  0.06116057]
 [ 0.75884939  0.08661501  0.05836962  0.09616598]
 [ 0.62097359  0.13794733  0.15715852  0.08392056]]
Calc ROC
Preprocessing data (1).
[[ 0.26261421  0.20209048  0.4370672   0.09822811]
 [ 0.15628277  0.1781048   0.54822087  0.11739156]
 [ 0.24468096  0.20983516  0.3242608   0.22122307]
 ..., 
 [ 0.57372334  0.23115142  0.13498655  0.06013869]
 [ 0.38670459  0.24346528  0.24110533  0.12872479]
 [ 0.46871942  0.3022865   0.14296728  0.08602681]]
[3 3 3 ..., 1 1 1]
Baseline AUC is:  {0: 0.99996212682662722, 1: 0.99993172956870668, 2: 0.99996736488783788, 3: 0.99986086891635195}
Wednesday AUC is:  {0: 0.99999984932097319, 1: 1.0, 2: 0.9999925761227586, 3: 1.0}

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier

def runModelThurSubmission(X,Y):
    print('Run model')
    
    # This is taken from the section notebook. The only modification is for the RFC which we have already
    # run a hyperparameter search on.
    
    #Build Model1 - Level 0
    Model1 = OneVsRestClassifier(RandomForestClassifier(
            n_estimators=50, 
            max_depth=32, 
            min_samples_split=4, 
            min_samples_leaf=4))
    Model1.fit(X,Y)

    #Predict on X_train, X_test
    Model1_pred_test = Model1.predict_proba(X)
    #Model1_pred_train = Model1.predict_proba(X_train)

    #Build Model3 - Level 0
    Model3 = OneVsRestClassifier(QuadraticDiscriminantAnalysis())
    Model3.fit(X,Y)
    Model3_pred_test = Model3.predict_proba(X)
    #Model3_pred_train = Model3.predict_proba(X_train)

    #Build Model5 - Level 0
    Model5 = OneVsRestClassifier(KNeighborsClassifier(n_neighbors=15, weights='distance'))
    Model5.fit(X,Y)
    Model5_pred_test = Model5.predict_proba(X)
    #Model5_pred_train = Model5.predict_proba(X_train)
    
    #Model 4 - Level 1 
    #Creating training attributes for Model4 (based on Model1, Model3, Model5 )
    FeaturesTest1 = np.hstack([Model1_pred_test,Model3_pred_test,Model5_pred_test])  
    Model4 = OneVsRestClassifier(LogisticRegression(random_state=49))
    Model4.fit(FeaturesTest1,Y)

    #Creating test attributes for Model3 (based on Model1 and Model2)
    #FeaturesTest1 = np.hstack([Model1_pred_test,Model3_pred_test,Model5_pred_test])

    #Final predictions
    final_pred = Model4.predict_proba(FeaturesTest1)

    #AUC
    #fpr, tpr, thresholds = roc_curve(Y, final_pred[:, 1])
    #roc_auc = auc(fpr, tpr)
    #print("AUC with Stacking: " , roc_auc)
    #Minor improvement with stacking over stand alone models
    
    return final_pred, Model4




# Clean up the data
X = preprocessFeatures3(XOrig)
Y = YOrig

# Run the model
Y_predict, clf = runModelThurSubmission(X,Y)

thurSubmissionAAUC = calculateROC(Y, Y_predict)

createSubmission(clf,preprocessData3)

Preprocessing data (3).
Run model
Calc ROC


NameError: name 'preprocessData3' is not defined

## Sunday Submission

Simply using Thursdays submission but removing some non-important features (TBD)

In [ ]:
def rank_to_dict(ranks, names, order=1):
    minmax = MinMaxScaler()
    ranks = minmax.fit_transform(order*np.array([ranks]).T).T[0]
    ranks = map(lambda x: round(x, 2), ranks)
    return dict(zip(names, ranks ))



def dropEstimators(X,Y):
    
    for i in range()
        clf = OneVsRestClassifier(RandomForestClassifier(n_estimators = 50,
                                                         max_depth = 32,
                                                         min_samples_split = 4,
                                                         min_samples_leaf = 4,
                                                         random_state=25))
        clf.fit(X,Y)

        for i in range(4):
            print(clf.estimators_[i].feature_importances_)
    
    
    
def runModelSatSubmission(X,Y):
    print('Run model')
    
    clf = OneVsRestClassifier(RandomForestClassifier(n_estimators = 50,
                                                     max_depth = 32,
                                                     min_samples_split = 4,
                                                     min_samples_leaf = 4,
                                                     random_state=25))
    clf.fit(X,Y)
    Y_predict = clf.predict_proba(X)
    
    return Y_predict, clf

#Split into training and test set - where the latter is 15% of the total 
#X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.15, random_state=10) 
#print (X.shape, X_train.shape, X_test.shape)

# Clean up the data
X = preprocessFeatures3(XOrig)
Y = YOrig

X = dropEstimators(X,Y)
#Y_predict, clf = runModelSatSubmission(X,Y)
#satSubmissionAAUC = calculateROC(Y, Y_predict)
#createSubmission(clf)


#print('Baseline AUC is: ', baselineAUC)
#print('Wednesday AUC is: ', satSubmissionAAUC)




In [15]:
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 11 06:21:10 2016

@author: rob
"""

from sklearn.feature_selection import RFECV
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import roc_curve, auc
from sklearn.grid_search import GridSearchCV   #Performing grid search
from sklearn.cross_validation import train_test_split

def readFiles():
    #Reading files
    X = pd.read_csv("trainingData.txt",sep='\t',header=None)
    Y = pd.read_csv("trainingTruth.txt",sep='\t',header=None)
    Y = np.array(Y).ravel()
    
    return (X,Y)


def preprocessFeatures3( X ):
    print('Preprocessing data (3).')

    # Q: Normalise data for SVMs - what about decision trees?
    

    #Rewrite this from the HW ipython book
    # Replace any NaN in X with the mean of the column
    # Replacing with the mean gives a better score
    xMean = []
    for col in X.columns:
        xMean = X[col].mean()
        #print(col, ' ', xMean)
        X.loc[X[col].isnull(), col] = xMean
    
    return (X)


def main():
    XOrig,YOrig = readFiles()
    
    X = preprocessFeatures3(XOrig)
    
    Y = label_binarize(YOrig, classes=[1, 2, 3, 4])

    #Split into training and test set - where the latter is 15% of the total 
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.15, random_state=10) 
    
    model = RandomForestClassifier(
                n_estimators=150, 
                max_depth=128, 
                min_samples_split=4, 
                min_samples_leaf=2,
                random_state=24,   
                oob_score=False)  
    
    all_rfecv = []
    
    i=1
    rfecv = RFECV(model, scoring='roc_auc', verbose=2, n_jobs=6)
    rfecv.fit(X_train, Y_train[:,i])
    rfecv.score(X_test, Y_test[:,i])
    print('Model {} Number Features {}'.format(i, rfecv.n_features_))
    print('Model {} Number Estimators {}'.format(i, rfecv.ranking_))
    print('Model {} Scores {}'.format(i, rfecv.grid_scores_))
    all_rfecv.append(rfecv)
    

main()

Preprocessing data (3).
Fitting estimator with 334 features.
Fitting estimator with 334 features.
Fitting estimator with 334 features.
Fitting estimator with 333 features.
Fitting estimator with 333 features.
Fitting estimator with 333 features.
Fitting estimator with 332 features.
Fitting estimator with 332 features.
Fitting estimator with 332 features.
Fitting estimator with 331 features.
Fitting estimator with 331 features.
Fitting estimator with 331 features.
Fitting estimator with 330 features.
Fitting estimator with 330 features.
Fitting estimator with 330 features.
Fitting estimator with 329 features.
Fitting estimator with 329 features.
Fitting estimator with 329 features.
Fitting estimator with 328 features.
Fitting estimator with 328 features.
Fitting estimator with 328 features.
Fitting estimator with 327 features.
Fitting estimator with 327 features.
Fitting estimator with 327 features.
Fitting estimator with 326 features.
Fitting estimator with 326 features.
Fitting estima

AttributeError: 'RFECV' object has no attribute 'best_estimators_'

In [ ]:
i=1 (Model2)

Model 2 Number Features 133

In [ ]:
createSubmission(clf,preprocessData3)


# The Final Solution

TBD

NB: When you run the sample (before upgrading) these are the values it produces: {0: 0.95755745500532141, 1: 0.94345356758244103, 2: 0.95754489510952012, 3: 0.935902875654121}